---
title: "PA2 - extended"
author: "lars pijnappel"
date: "12 augustus 2015"
output: html_document
---

#Topic
This topic is extending on the [Programming Assignment 2][PA2] page (originally created by DanieleP) and covers how to validate your assignment by following a couple of test steps ([originally provided by Thiago Kurovski][rprog-031]). Also, as pointed out by Louis Alexander McLennan, the following YouTube video on [function closures and free variables][closures101], might be helpful as well. 

Many thanks to all of you, it sure helped me a lot!

#Intro 
The Programming Assignment 2 from the course R Programming of the [Coursera Data Science Specialization][cdss]) concerns writing two R functions, which appears to be very challenging for many participants.

Based on the provided [example functions][rdpeng], the task is to write a similar solution for *caching the inverse of a matrix* (for an explanation on inverse of a matrix see [Mathwords][mw] or [Wolfram MathWorld][wolfram]). 

One might forget that the task is not really about creating functions which must be fully operational - the evaluation instructions for this peer assessment state explicitely that the *R code should not be run on the computer*. Nevertheless, it is very interesting to see it all working in order to get a better understanding of what these functions are all about. For this reason, the next section describes possible test steps which can be executed on your own code.

##Important!
Please note that these test cases do not cover all requirements as specified for this assignment, nor is it intended to validate the completeness of the task. Advise is to read (and re-read!) the assignment completely - including the evaluation criteria at the bottom of the page as well...

#Test Cases
```{r eval=FALSE}
## Check if creating a cacheMatrix and getting its content works fine
x1 <- matrix(rnorm(1000000), nrow = 1000)   # matrix 1
x2 <- matrix(rnorm(1000000), nrow = 1000)   # matrix 2
cm <- makeCacheMatrix( x1 )
identical( cm$get(), x1 )   ## TRUE
identical( cm$get(), x2 )   ## FALSE

## Check if cacheSolve gives the same result for the same matrix and if it truly uses caching
print(system.time( y1 <- cacheSolve(cm) ))  # 1st time calling cacheSolve: requires some calculation time
print(system.time( y2 <- cacheSolve(cm) ))  # 2nd time: same output but stating that cached data is used
identical( y1, y2 ) # TRUE
identical( y1, x2 ) # FALSE

## Check if cacheSolve gives the same result as solve()
z <- solve( x1 )
identical( y1, z )  # TRUE

## Check if updating the matrix with set works correctly
x3 <- matrix(rnorm(100), nrow = 10)
cm$set( x3 )
identical( cm$get(), x3 )    # TRUE

## Check if the cache is unvalidated after a set()
y3 <- cacheSolve( cm )
z <- solve( x3 )
identical( y3 , z ) # TRUE
```



[PA2]: https://github.com/DanieleP/PA2-clarifying_instructions 'PA2-clarifying_instructions'
[rprog-031]: https://class.coursera.org/rprog-031/forum/thread?thread_id=112#post-468
[closures101]: https://www.youtube.com/watch?v=yiEeiMN2Khs
[cdss]: https://www.coursera.org/specialization/jhudatascience/1 'Data Science course by Johns Hopkins University'
[rdpeng]: https://github.com/rdpeng/ProgrammingAssignment2
[mw]: http://www.mathwords.com/i/inverse_of_a_matrix.htm
[wolfram]: http://mathworld.wolfram.com/MatrixInverse.html